-- New EventType values for the direct-order autonomous chain
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TICKET_BACKFILL_RESOLVED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SUPPLIER_RFQ_LINKED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SUPPLIER_PRICES_EXTRACTED';
